### ISSUE TITLE
Doesn't compile on Linux with R >= 4.3

### ISSUE THREAD

**Issue by nshrine** [jolars/eulerr#117]
Engine.cpp: error: 'Rf_allocLang' was not declared in this scope
In file included from .../R/include/Rdefines.h

Recent R releases have removed or deprecated parts of the old API that GenSA still uses, so the error
comes from the fact that Rdefines.h is considered legacy and no longer fully supported for new code.
Some macros/functions (including Rf_allocLang) are no longer exposed unless very old compatibility flags are set.
New R recommends including Rinternals.h directly and using its constructors and PROTECT discipline.

**Comment by jolars** [comment]
Thanks for the report! But I cannot reproduce this locally (also on Linux). The CI job also works fine: https://github.com/jolars/eulerr/actions/workflows/R-CMD-check.yaml

And the CRAN  checks as of today are also good: https://cran.r-project.org/web/checks/check_results_eulerr.html

Are you sure this isn't something on your end?
